config/routes.rb
Rails.application.routes.draw do

   root 'welcome#home'

   resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def new
    @trip=Trip.new
  end

  def create
    @trip=Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path, notice: "Trip successfully created"
    else
      render :new
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    if @trip.save
      redirect_to trips_path, notice: "Trip successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path, notice: "Trip successfully deleted"
  end

  private

  def trip_params
    params.require(:trip).permit(
      :name,
      :date_of_trip,
      :location,
      :activities,
      :trip_type,
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GProjects</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="#">uPack</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Trips', trips_path %></li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Username<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Sign-Off</a></li>
              <li><a href="#">Settings</a></li>
              <li><a href="#">Privacy</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


    <% if notice %>
      <div class="alert alert-success">
        <p class="text-center"><%= notice %><p>
      </div>
    <% end %>


  <div class="container">
    <%= yield %>
  </div>

  <div class= "footer">
  </div>


</body>
</html>

app/views/trips/edit.html.erb
<div class="page-header">
  <h1>Editing <%=@trip.name.capitalize %> Trip </h1>
</div>

<%= form_for(@trip, html: {class:"form-horizontal" }) do |f| %>
<% if @trip.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved: </h2>
  <ul>
    <% @trip.errors.full_messages.each do |message| %>
    <li><%= message %> </li>
    <% end %>
  </ul>
</div>
<% end %>

<div class ="form-group" %>
  <%= f.label :name, class: "col-md-2 control-label"%>
  <div class= "col-md-4">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class ="form-group" %>
  <%= f.label :date_of_trip, class: "col-md-2 control-label"%>
  <div class= "col-md-4">
    <%= f.date_field :date_of_trip, class: "form-control" %>
  </div>
</div>

<div class ="form-group" %>
  <%= f.label :location, class: "col-md-2 control-label"%>
  <div class= "col-md-4">
    <%= f.text_area :location, class: "form-control" %>
  </div>
</div>

<div class ="form-group" %>
  <%= f.label :activities, class: "col-md-2 control-label"%>
  <div class= "col-md-6">
    <%= f.select :activities, ["hiking/climbing", "safari", "religious sight seeing", "beach bumming"], class: "form-control" %>
  </div>
</div>

<div class ="form-group" %>
  <%= f.label :trip_type, class: "col-md-2 control-label"%>
  <div class= "col-md-6">
    <%= f.select :trip_type, ["backpacking", "luxury", "outdoor adventure", "beach", "historical tour"], class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-md-offset-2 col-md-6">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", :back, class: "btn btn-default" %>
  </div>
</div>

<% end %>

app/views/trips/index.html.erb
<div class="page-header">
  <%= link_to "New Trip", new_trip_path, class: "btn btn-info pull-right" %>
  <h1>Your Trips</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th> Trip Name </th>
      <th> Date </th>
      <th> Location </th>
      <th> Duration </th>
      <th colspan= "3"></th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%=link_to trip.name, trip %></td>
        <td><%= trip.date_of_trip %></td>
        <td><%= trip.location %></td>
        <td>Still figuring out duration</td>
        <td><%= link_to "Show", trip_path(trip), class: "btn btn-default"%></td>
        <td><%= link_to "Edit", edit_trip_path(trip), class: "btn btn-default" %></td>
        <td><%= link_to "Delete", trip, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trips/new.html.erb
<div class="page-header">
  <h1>New Trip</h1>
</div>

<%= form_for(@trip, html: {class:"form-horizontal" }) do |f| %>
  <% if @trip.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved: </h2>
    <ul>
      <% @trip.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class ="form-group" %>
    <%= f.label :name, class: "col-md-2 control-label"%>
    <div class= "col-md-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class ="form-group" %>
    <%= f.label :date_of_trip, class: "col-md-2 control-label"%>
    <div class= "col-md-4">
      <%= f.date_field :date_of_trip, class: "form-control" %>
    </div>
  </div>

  <div class ="form-group" %>
    <%= f.label :location, class: "col-md-2 control-label"%>
    <div class= "col-md-4">
      <%= f.text_area :location, class: "form-control" %>
    </div>
  </div>

  <div class ="form-group" %>
    <%= f.label :activities, class: "col-md-2 control-label"%>
    <div class= "col-md-6">
      <%= f.select :activities, ["hiking/climbing", "safari", "religious sight seeing", "beach bumming"], class: "form-control" %>
    </div>
  </div>

  <div class ="form-group" %>
    <%= f.label :trip_type, class: "col-md-2 control-label"%>
    <div class= "col-md-6">
      <%= f.select :trip_type, ["backpacking", "luxury", "outdoor adventure", "beach", "historical tour"], class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", :back, class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/trips/show.html.erb
<div class= "page-header">
  <h1><%= "#{@trip.name}"%></h1>
</div>

<dl>
  <dt><strong>Location</strong></dt>
  <dd><%= @trip.location %></dd>

  <dt><strong>Date of Trip</strong></dt>
  <dd><%= @trip.date_of_trip %></dd>

  <dt><strong>Location</strong></dt>
  <dd><%= @trip.location %></dd>

  <dt><strong>Activities</strong></dt>
  <dd><%= @trip.activities %></dd>

  <dt><strong>Type of Trip</strong></dt>
  <dd><%= @trip.trip_type %></dd>

</dl>

<%= link_to "Edit", edit_trip_path, class:"btn btn-default" %>
<%= link_to "Back", :back, class:"btn btn-default" %>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <h1>uPack</h1>
  <p>Your trips with more direction</p>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "image_1.jpg", class: "img-responsive" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "image_2.jpg", class: "img-responsive" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <%= image_tag "image_3.jpg", class: "img-responsive" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Trips</h3>
      </div>
      <div class="panel-body">
        Your trips with a little more organization and guidance.
        Give us the date and time of your trip and we'll tell you
        what to pack and what other people are packing for a trip like
        yours. This includes cultural, weather and activity related tips.
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Dream Trips</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li>Connect to your travel inspiration on Pinterest</li>
          <li>See other trip resources in one place</li>
          <li>Check what others are planning</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Documents</h3>
      </div>
      <div class="panel-body">
        <ul>
          <li>Not sure what to put here... </li>
          <li>What's my third panel?!?!</li>
        </ul>
      </div>
    </div>
  </div>
</div>